[package]
name = "tetanus"
license = "MIT"
description = "A custom utils library for some common unsafe operations"
version = "0.3.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
